apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "training-router.fullname" . }}
  namespace: {{ include "training-router.namespace" . }}
spec:
  host: {{ include "training-router.fullname" . }}.{{ include "training-router.namespace" . }}.svc.cluster.local
  workloadSelector:
    matchLabels:
      {{- include "training-router.labels" . | nindent 6 }}
