apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-client.fullname" . }}
  namespace: {{ include "postgresql-client.namespace" . }}
  labels:
    {{- include "postgresql-client.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "postgresql-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql-client.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "postgresql-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          stdin: true
          tty: true
          command: ["/bin/sh"]
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m
