application:
  namespace: sample
image:
  repository: pmaierean/postgresql-client
  pullPolicy: IfNotPresent
  tag:

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

database:
  port: 5432
  address: 192.168.1.177
  name: tcp
  host: postgres
  longName: localhost.postgres.com

service:
  type: ClusterIP
  port: 8090

fullnameOverride: false
nameOverride: ""

podSecurityContext: {}

securityContext: {}