apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "training-boot.fullname" . }}-pv
  namespace: {{ include "training-boot.namespace" . }}
  labels:
    {{- include "training-boot.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.path }}
