application:
  namespace: sample

replicaCount: 1

image:
  repository: pmaierean/training-app
  pullPolicy: IfNotPresent
  tag:

database:
  #host: simple-postgres
  host: 192.168.1.177
  port: 5432
  user: postgres
  password: zG14#23ABC9926$

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080


livenessProbe:
  initialDelaySeconds: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volume:
  path: /opt/app/local/sample1
  affinityNode: minikube
