apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "external-postgresql.fullname" . }}
  namespace: {{ include "external-postgresql.namespace" . }}
  labels:
    {{- include "external-postgresql.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "external-postgresql.fullname" . }}.{{ include "external-postgresql.namespace" . }}.svc.cluster.local
  tcp:
    - match:
      - port: {{ .Values.database.port }}
      route:
        - destination:
             host: {{ .Values.database.host }}
