name: training-app
services:
  PostgreSQL:
    image: pmaierean/maiereni_postgresql:0.1
    build:
      context: Database
      dockerfile: Dockerfile
    container_name: postgresql
    env_file:
      - ./Database/.env
    ports:
      - 54322:5432
    restart: always
  liquidbase:
    image: pmaierean/maiereni_liquidbase:0.2
    build:
      context: Liquibase
      dockerfile: Dockerfile
    container_name: liquibase
    env_file:
      - ./Database/.env
    depends_on:
      PostgreSQL:
        condition: service_started
    volumes:
      - ./Database/src/main/resources/:/liquibase/changelog/
  training-ui:
    image: pmaierean/training-app-ui:0.2
    build:
      context: SampleUI
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    restart: always
  training-boot:
    image: pmaierean/training-app:0.3
    build:
      context: Sample
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5009:5009
    volumes:
      - "D:/opt/app/local/sample:/opt/app/local/sample"
    env_file:
      - .env
    depends_on:
      liquidbase:
        condition: service_completed_successfully
    restart: always
  training-router:
    image: pmaierean/training-router:0.4
    build:
      context: Router
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - DOMAIN_BOOT=training-boot
      - DOMAIN_UI=training-ui
    depends_on:
      training-boot:
        condition: service_started

