apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "training-ui.fullname" . }}
  namespace: {{ include "training-ui.namespace" . }}
  labels:
    {{- include "training-ui.labels" . | nindent 4 }}
spec:
  hosts:
   - {{ include "training-ui.fullname" . }}.{{ include "training-ui.namespace" . }}.svc.cluster.local
  http:
   - name: "{{ include "training-ui.fullname" . }}-routes"
     match:
       - uri:
           prefix: "/"
     route:
       - destination:
             host: {{ include "training-ui.fullname" . }}.{{ include "training-ui.namespace" . }}.svc.cluster.local
