kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "postgresql-client.serviceAccountName" . }}
  namespace: {{ include "postgresql-client.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "postgresql-client.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "postgresql-client.serviceAccountName" . }}