apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: istio-system
spec:
  type: ExternalName
  externalName: prometheus-grafana.monitoring.svc.cluster.local
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: istio-system
spec:
  type: ExternalName
  externalName: prometheus-operated.monitoring.svc.cluster.local
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
