spring:
  application:
     name: Sample
  jpa:
    database: postgresql
    mapping-resources:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
logging:
  level:
     com.maiereni.webapp: debug