apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-cluster.secretname" . }}
  namespace: {{ include "postgresql-cluster.namespace" . }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.database.user | b64enc }}
  password: {{ .Values.database.password | b64enc }}