apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-cluster.supersecretname" . }}
  namespace: {{ include "postgresql-cluster.namespace" . }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.database.root | b64enc }}
  password: {{ .Values.database.rootPassword | b64enc }}