apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "postgresql-cluster.fullname" . }}
  namespace: {{ include "postgresql-cluster.namespace" . }}
  labels:
    {{- include "postgresql-cluster.labels" . | nindent 4 }}
spec:
  hosts:
    - "{{ include "postgresql-cluster.fullname" . }}-rw.{{ include "postgresql-cluster.namespace" . }}.svc.cluster.local"
  http:
    - name: "{{ include "postgresql-cluster.fullname" . }}-routes"
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: "{{ include "postgresql-cluster.fullname" . }}-rw.{{ include "postgresql-cluster.namespace" . }}.svc.cluster.local"